package model.enums;

public enum Capacidad {
    PREGRADO,
    MAESTRIA,
    DOCTORADO,
    EXPERIENCIA_LABORAL,
    ADAPTABILIDAD,
    COMUNICACION,
    RESOLUCION_PROBLEMAS,
    CREATIVIDAD,
    CONFIANZA,
    HONESTIDAD,
    PACIENCIA
}
